# -*- coding: utf-8 -*-
"""APCSP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZmf-pqaaXfQ8J4_B413brxcOzcKmpcq
"""

from google.colab import output
def addItemToDo(name, priority):
    todo.append([name, priority])

def findHighestPriority(minpriority):
    if len(todo)==0:
      print("Error, Empty List")
      return
    maximum = minpriority
    maximumindex = -1
    for i in range(len(todo)):
      current = todo[i][1]
      if current>maximum:
        maximum = current
        maximumindex = i
    if maximumindex != -1:
      print("Next Task:")
      print("-"*60)
      printOneTask(maximumindex)
      print("-"*60)
    else:
      print("Minimum Criteria not met")
      return


def printOneTask(number):
    print(f"Number: {number+1:<3}| Name: {todo[number][0]:<15} | Priority: {todo[number][1]:<4} |")

def printTodo():
    if len(todo)>0:
        print("Your Current List:")
        print("-"*60)
        for i in range(len(todo)):
            printOneTask(i)
    else:
        print("Your list is empty")
    print("-"*60)

def finishItemToDo(index):
    todo.remove(todo[index])


todo = []
print("Welcome to your To-Do list!")

while True:
    printTodo()
    choice = int(input("Press 1 to add an task, 2 to cross off a task, and 3 for your next task"))
    if (choice==1):
        addItemToDo(str(input("Task name?")),int(input("Task Priority?")))
    elif (choice==2):
        finishItemToDo(int(input("Task Number?"))-1)
    elif (choice == 3):
        output.clear()
        findHighestPriority(int(input("Minimum Priority?")))
        str(input("Press anything to continue"))
    else:
        print("Invalid input, please try again.")
    output.clear()